apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: acm-cert-aws-smoketest
  labels:
    app.kubernetes.io/managed-by: kubernova
    kubernova.io/platform: smoketest
    kubernova.io/service: acm-cert
    kubernova.io/provider: aws
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: security.smoketest.kubernova.io/v1alpha1
    kind: XAcmCertificate
  mode: Pipeline
  pipeline:
  - step: render
    functionRef:
      name: fn-aws-acm-cert
    input:
      apiVersion: fn-aws-acm-cert.kubernova.io/v1alpha1
      kind: Input
      spec:
        platform: smoketest
        service: acm-cert
        provider: aws
  - step: auto-ready
    functionRef:
      name: function-auto-ready
