apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: eks-aws-smoketest
  labels:
    app.kubernetes.io/managed-by: kubernova
    kubernova.io/platform: smoketest
    kubernova.io/service: eks
    kubernova.io/provider: aws
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: compute.smoketest.kubernova.io/v1alpha1
    kind: XEks
  mode: Pipeline
  pipeline:
  - step: render
    functionRef:
      name: fn-eks-cluster
    input:
      apiVersion: fn-eks-cluster.kubernova.io/v1alpha1
      kind: Input
      spec:
        platform: smoketest
        service: eks
        provider: aws
  - step: auto-ready
    functionRef:
      name: function-auto-ready
