apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoketest-production-aws-claims
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: kubernova
    kubernova.io/environment: production
    kubernova.io/provider: aws
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    kubernova.io/owns-claims: AcmCertificate/alb-acm-cert,AcmCertificate/alb-acm-cert-2,AcmCertificate/alb-acm-cert-3,ApplicationLoadBalancer/http-gateway-1781065888219,ApplicationLoadBalancer/load-balancer-1781065939734,ApplicationLoadBalancer/load-balancer-1781072119725,Eks/http-api-1781065949848,KmsKey/rds-kms,Network/alb-vpc,Rds/relational-db-1781065952773
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asheenn/smoke-web-stack.git
    targetRevision: main
    path: platforms/smoketest/production/smoke-1781072025/claims
    directory:
      include: claims.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
