apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoketest-smoke-lambda-1781118093-claims
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/asheenn/smoke-web-stack.git
    targetRevision: main
    path: platforms/smoketest/envs/production/smoke-lambda-1781118093/claims
    directory:
      include: claims.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
