---
apiVersion: compute.smoketest.kubernova.io/v1alpha1
kind: Lambda
metadata:
  name: serverless-fn
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kubernova
    kubernova.io/platform: smoketest
    kubernova.io/env-type: production
    kubernova.io/env-name: smoke-lambda-1781118093
spec:
  parameters:
    region: us-east-1
    runtime: nodejs20.x
    memoryMb: 512
    timeoutSeconds: 30
    handler: index.handler
---
apiVersion: compute.smoketest.kubernova.io/v1alpha1
kind: ApiGatewayHttp
metadata:
  name: http-gateway
  namespace: default
  labels:
    app.kubernetes.io/managed-by: kubernova
    kubernova.io/platform: smoketest
    kubernova.io/env-type: production
    kubernova.io/env-name: smoke-lambda-1781118093
spec:
  parameters:
    region: us-east-1
    protocolType: HTTP
